# numpy学习 7班

### 作业说明：
####    代码没有标准答案，但是代码有好坏之分，衡量好坏的标准：
####    1 代码的时间复杂度
####    2 代码的空间复杂度
####    3 代码书写的规范：是否符合语言规范，命名是否清晰易懂，代码是否整洁 《代码整洁之道》，代码是否重复(代码不要重复)
            # don't repeat yourself !!! dry原则

In [5]:
import numpy as np

In [9]:
a = np.array([2,3,4,1,6]) # array数组 使用numpy的array api创建一个一维数组
print(a)

[2 3 4 1 6]


In [14]:
# 求a的最大值
print(a.max())

6


In [16]:
type(a)  # a是numpy.ndarray类型,不是list类型了   ndarray：n dimension array n纬数组

numpy.ndarray

In [17]:
type([2,3,45])

list

### numpy.ndarray对象中常用的api

In [29]:
a = np.array([2,3,4,1,6])
b = np.array([[5,2],[2,6],[6,4]])
c = np.array([[[8,5,2],[5,6,7]]    ,    [[2,6,3],[6,4,3]]])

In [32]:
print(a.shape) # shape形状。。。  结果(5,)的括号中只有一个数字，说明数组a是1维的，并且第一层有5个元素
print(b.shape) # (3,2)，圆括号中有两个数字，表示一个二维矩阵，第一层有3个元素，第二层有2个元素
print(c.shape)

(5,)
(3, 2)
(2, 2, 3)


In [41]:
print(f'{a.max()} | {b.max()} | {c.max()}') # 函数起名字尽量用动词  max min 最大最小

6 | 6 | 8


In [45]:
print(f'{a.ndim} | {b.ndim} | {c.ndim}') # ndim: n dimension 查看矩阵的维度

1 | 2 | 3


In [49]:
print(f'{a.size} | {b.size} | {c.size}') # size大小 查看矩阵中元素的个数

5 | 6 | 12


In [53]:
print(f'{a.dtype} | {b.dtype} | {c.dtype}') # dtype: data type 数据类型。

int64 | int64 | int64


In [65]:
a = np.array([2,3,-129,127,6],dtype='int8') # int8范围是 [-128,127]
b = np.array([[5,2],[2,6],[6,4]])
c = np.array([[[8,5,2],[5,6,7]]    ,    [[2,6,3],[6,4,3]]])
print(f"a={a}")
print(f'{a.dtype} | {b.dtype} | {c.dtype}')

a=[  2   3 127 127   6]
int8 | int64 | int64


# numpy生成矩阵

In [81]:
a = np.zeros((3,5))  # zero:0 生成一个3x5的二维矩阵，元素都是0
print(a)
print(a.shape)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(3, 5)


In [83]:
b = np.ones((2,6)) # 生成一个二维矩阵，用1填充
print(b)
print(b.shape)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
(2, 6)


In [90]:
c = np.full((5,5), 10) # 生成一个5x5的二维矩阵，用10填充
print(c)
print(c.shape)

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]
(5, 5)


In [92]:
d = np.full_like(c, 11) # like好像。   创建一个跟c的shape一样的二维数组，用11填充
print(d)

[[11 11 11 11 11]
 [11 11 11 11 11]
 [11 11 11 11 11]
 [11 11 11 11 11]
 [11 11 11 11 11]]


# numpy生成随机数/随机矩阵