# numpy学习 7班

### 作业说明：
####    代码没有标准答案，但是代码有好坏之分，衡量好坏的标准：
####    1 代码的时间复杂度
####    2 代码的空间复杂度
####    3 代码书写的规范：是否符合语言规范，命名是否清晰易懂，代码是否整洁 《代码整洁之道》，代码是否重复(代码不要重复)
            # don't repeat yourself !!! dry原则

In [5]:
import numpy as np

In [9]:
a = np.array([2,3,4,1,6]) # array数组 使用numpy的array api创建一个一维数组
print(a)

[2 3 4 1 6]


In [14]:
# 求a的最大值
print(a.max())

6


In [16]:
type(a)  # a是numpy.ndarray类型,不是list类型了   ndarray：n dimension array n纬数组

numpy.ndarray

In [17]:
type([2,3,45])

list

### numpy.ndarray对象中常用的api

In [29]:
a = np.array([2,3,4,1,6])
b = np.array([[5,2],[2,6],[6,4]])
c = np.array([[[8,5,2],[5,6,7]]    ,    [[2,6,3],[6,4,3]]])

In [32]:
print(a.shape) # shape形状。。。  结果(5,)的括号中只有一个数字，说明数组a是1维的，并且第一层有5个元素
print(b.shape) # (3,2)，圆括号中有两个数字，表示一个二维矩阵，第一层有3个元素，第二层有2个元素
print(c.shape)

(5,)
(3, 2)
(2, 2, 3)


In [41]:
print(f'{a.max()} | {b.max()} | {c.max()}') # 函数起名字尽量用动词  max min 最大最小

6 | 6 | 8


In [45]:
print(f'{a.ndim} | {b.ndim} | {c.ndim}') # ndim: n dimension 查看矩阵的维度

1 | 2 | 3


In [49]:
print(f'{a.size} | {b.size} | {c.size}') # size大小 查看矩阵中元素的个数

5 | 6 | 12


In [53]:
print(f'{a.dtype} | {b.dtype} | {c.dtype}') # dtype: data type 数据类型。

int64 | int64 | int64


In [65]:
a = np.array([2,3,-129,127,6],dtype='int8') # int8范围是 [-128,127]
b = np.array([[5,2],[2,6],[6,4]])
c = np.array([[[8,5,2],[5,6,7]]    ,    [[2,6,3],[6,4,3]]])
print(f"a={a}")
print(f'{a.dtype} | {b.dtype} | {c.dtype}')

a=[  2   3 127 127   6]
int8 | int64 | int64


# numpy生成矩阵

In [81]:
a = np.zeros((3,5))  # zero:0 生成一个3x5的二维矩阵，元素都是0
print(a)
print(a.shape)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(3, 5)


In [83]:
b = np.ones((2,6)) # 生成一个二维矩阵，用1填充
print(b)
print(b.shape)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
(2, 6)


In [90]:
c = np.full((5,5), 10) # 生成一个5x5的二维矩阵，用10填充
print(c)
print(c.shape)

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]
(5, 5)


In [92]:
d = np.full_like(c, 11) # like好像。   创建一个跟c的shape一样的二维数组，用11填充
print(d)

[[11 11 11 11 11]
 [11 11 11 11 11]
 [11 11 11 11 11]
 [11 11 11 11 11]
 [11 11 11 11 11]]


# numpy生成随机数/随机矩阵

In [209]:
a = np.random.rand(3,3) # 随机生成一个2x2的矩阵 元素范围是(0-1)
print(a)

[[0.05159297 0.79491726 0.90693841]
 [0.12372394 0.22623117 0.05371311]
 [0.70301946 0.98410322 0.16368649]]


In [334]:
# 如何得到一个随机数 骰子
i = np.random.randint(1,10) # 产生一个随机的整数。 《计算机程序设计艺术》高德纳 图灵奖   伪随机数
print(i)

4


In [404]:
a = np.random.randint(100,size=(3,3)) # 创建一个随机的矩阵3x3  元素的范围是[0,99]
print(a)
a = np.random.randint(1,100,size=(3,3))  # 创建一个随机的矩阵3x3  元素的范围是[1,99]
print(a)

[[ 7 47 71]
 [55 85 82]
 [ 8 67 69]]
[[22 92 93]
 [50 86 22]
 [75 67 28]]


In [418]:
b = np.random.sample(a.shape) #sample例子。 按照a的shape形状 创建一个随机矩阵，元素是[0,1)之间的随机数
print(b)

[[0.52587159 0.62487733 0.28694684]
 [0.95032263 0.70005226 0.74216175]
 [0.5370679  0.1699794  0.90077354]]


In [439]:
b = np.random.randint(1,100,size=a.shape)
print(b)

[[81 22 21]
 [60 26  8]
 [29 57 20]]


### numpy 复制 矩阵

In [443]:
a = np.array([1,2,3])
b = np.repeat(a,2)  # re重复 再   rename. fefactor重构
print(b)

[1 1 2 2 3 3]


In [445]:
a = np.array([[1,2],[3,4],[5,6]])
b = np.repeat(a,2)
print(b)

[1 1 2 2 3 3 4 4 5 5 6 6]


# axis层级  axis=0代表第1层。axis=1代表第2层。axis=2代表第3层，但a是2纬度矩阵，没有第3层，所以报错。

In [450]:
a = np.array([[1,2],[3,4],[5,6]])  # a现在是一个2维矩阵。a有2个维度，也就是有两层
b = np.repeat(a,2,axis=2) 
print(b)

AxisError: axis 2 is out of bounds for array of dimension 2

In [456]:
a = np.array([[1,2],[3,4],[5,6]])  # a现在是一个2维矩阵。a有2个维度，也就是有两层
b = np.repeat(a,2,axis=1) # axis层级  axis=0代表第1层。axis=1代表第2层。axis=2代表第3层，但是a没有第3层，所以报错。
print(b)

[[1 1 2 2]
 [3 3 4 4]
 [5 5 6 6]]


In [467]:
c = np.array([[[8,5,2],[5,6,7]] , [[2,6,3],[6,4,3]]])
b = np.repeat(c,2,axis=0) # axis层级  axis=0代表第1层。axis=1代表第2层。axis=2代表第3层，但是a没有第3层，所以报错。
print(b)

[[[8 5 2]
  [5 6 7]]

 [[8 5 2]
  [5 6 7]]

 [[2 6 3]
  [6 4 3]]

 [[2 6 3]
  [6 4 3]]]


In [472]:
a = np.identity(5) # 生成一个3x3矩阵，而且这个矩阵是一个 单位矩阵：identity matrix
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [473]:
### 矩阵的索引，切隔

In [505]:
a = np.array([2,3,4,1,6])
b = np.array([[5,2,12,3,4],[2,61,2,3,4],[6,5,3,2,4]])
c = np.array([[[8,5,2],[5,6,7]]    ,    [[2,6,3],[6,4,3]]])

In [492]:
a[0:3]

array([2, 3, 4])

In [493]:
print(b[2][1])
print(b[2,1])

5
5


In [513]:
print(b[0][2:5])
print(b[0,2:5])

[0.]
[0.]


In [521]:
a = np.array([2,3,4,5])
b = a  # 此处赋值是赋的引用
b[0] = 1
print(a)
print(b)

[1 3 4 5]
[1 3 4 5]


## 复制的时候要注意了！！！

In [520]:
a = np.array([2,3,4,5])
b = a.copy()  # 此处赋值是赋的值
b[0] = 1
print(a)
print(b)

[2 3 4 5]
[1 3 4 5]


# 练习1 ： 生成一个符合图片要求的矩阵

In [510]:
a = np.ones((5,5))
b = np.zeros((3,3))
b[1,1] = 9  # 将b中间的值改成9
a[1:-1,1:-1] = b   # 将a中中间的区域替换成b
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# 练习2 ： 加载txt文件中的矩阵数据

In [544]:
'''
不用numpy，获取fdata.txt中的数据
'''
f = open("fdata.txt","r", encoding='utf-8')  # 有的同学的文件编码是 gbk
lines = f.readlines() # 读取所有的行

# TODO 此处定义一个二维的列表 alldatas

for line in lines:
    #print(line)
    # 去掉换行符
    line = line.replace("\n","")
    # 将数据按照逗号 切开
    numbers = line.split(",")
    #print(numbers)
    
    # 此处定义一个一维的列表 rows
    
    for number in numbers:
        
        # TODO 此处 rows.append(number)
        
        print(number, end='\t') # end="" 不换行
    print()
    # TODO 此处 alldatas.append(rows)

    ### TODO 将所有的数据放到一个 list 中

# 下面这种方式也行
#for line in f:
#    print(line)

1	2	3	4	5	6	
7	6	4	3	2	1	
5	6	7	8	9	3	
5	4	3	4	5	6	


# 下面的代码是使用numpy加载txt中的数据

In [539]:
import numpy as np

arr = np.genfromtxt("fdata.txt",delimiter=',') # 加载 fata.txt中的数据，用逗号切开，得到一个numpy.ndarray对象arr

In [540]:
print("修改之前的数据类型:",arr.dtype)

修改之前的数据类型: float64


In [541]:
# 修改arr的默认数据类型 float64 -> int8
arr = arr.astype('int8')
print("修改之后的数据类型:",arr.dtype)

修改之后的数据类型: int8


In [542]:
print(arr)

[[1 2 3 4 5 6]
 [7 6 4 3 2 1]
 [5 6 7 8 9 3]
 [5 4 3 4 5 6]]


In [545]:
print(type(arr))
print(arr.shape)

<class 'numpy.ndarray'>
(4, 6)


In [546]:
# 完整的代码
import numpy as np

arr = np.genfromtxt("fdata.txt",delimiter=',') # 加载 fata.txt中的数据，用逗号切开，得到一个numpy.ndarray对象arr
arr = arr.astype('int8')
print(arr)

[[1 2 3 4 5 6]
 [7 6 4 3 2 1]
 [5 6 7 8 9 3]
 [5 4 3 4 5 6]]


In [547]:
# 矩阵的点乘 算术乘

In [549]:
a = np.array([2,3,4,1,6]) 
b = np.array([12,23,24,11,16]) 
a*b

array([24, 69, 96, 11, 96])

In [554]:
# 点乘: 左边矩阵的行 乘以。右边矩阵的列
a = np.array([[1,2],[3,4]]) 
b = np.array([[5,6],[7,3]]) 
np.dot(a,b)

array([[19, 12],
       [43, 30]])