# numpy授课代码 周靖轩

In [1]:
import numpy as np

In [2]:
'''
快捷键: 
    回车 换行
    shift回车 换行
    ctrl+回车 运行+换行
    alt+回车  运行
'''

'\n快捷键: \n    回车 换行\n    shift回车 换行\n    ctrl+回车 运行+换行\n    alt+回车  运行\n'

In [334]:
a = np.array([1,2,3,4,5],dtype='int8')  # a是一个 ndarray类型的一维数组
b = np.array([[1,2,3],[1,3,4]])
c = np.array([[[11,12,13],
               [23,24,25]] ,
              [[35,360,37],
               [46,47,48]]])

In [32]:
print(a.shape, '|', b.shape, '|', c.shape) # 查看数组的形状

(5,) | (2, 3) | (2, 2, 3)


In [33]:
print(a.ndim,'|',  b.ndim, '|',  c.ndim) # ndim: n dimension n维  查看数组的维度

1 | 2 | 3


In [34]:
print(a.size, '|', b.size, '|', c.size) # size(大小) 元素的个数

5 | 6 | 12


In [56]:
print(a.max(),b.max(), c.max(),"|", a.min(), b.min(), c.min() ) # max:最大值    min:最小值 axis=0代表第一次

5 4 360 | 1 1 11


In [76]:
## 查看数据的类型
a = np.array([1,2,-128,127,5],dtype='int8')  # int8最大表示-128～127
atype = a.dtype # dtype: data type数据类型
print(f'a={a} | a类型:{atype}')

a=[   1    2 -128  127    5] | a类型:int8


In [52]:
d = np.zeros((2,3)) # 生成一个指定维度的数组，值全部是0
e = np.ones((5,5))
f = np.identity(5) # 生成一个 秩为5的单位矩阵 

In [77]:
print(d)
print(e)
print(f)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [92]:
g = np.full((2,3), -1) # full填充  创建一个新的矩阵数组，指定矩阵的维度(2,3)和默认值-1
h = np.full(b.shape, 3)
print(g)
print(h)

[[-1 -1 -1]
 [-1 -1 -1]]
[[3 3 3]
 [3 3 3]]


In [95]:
i = np.full_like(c, 9)
print(i)

[[[9 9 9]
  [9 9 9]]

 [[9 9 9]
  [9 9 9]]]


In [166]:
# 随机生成一个2x2的矩阵，随机数介于0～1之间
j = np.random.rand(3,3)
print(j)

[[0.69921686 0.80894285 0.71596109]
 [0.49281296 0.78667522 0.83670803]
 [0.53782912 0.93178151 0.08995131]]


In [267]:
# 随机生成一个随机数,整数.. 《计算机程序设计艺术》随机数的生成算法，伪随机。如果现在要有一个【随机】整数1～6之间，怎么产生？？？掷骰子
# TODO 考虑一下，如何用代码生成真正的随机数？
k = np.random.randint(1,10)  # 随机数的范围： [1,9] 或者 [1,10)
print(k)

7


In [271]:
np.random.random_sample(c.shape) #生成一个类似于c的随机矩阵  sample："例子"的意思  c.shape: (2,2,3)

array([[[0.49990346, 0.65078886, 0.98299948],
        [0.80350632, 0.68440337, 0.8606641 ]],

       [[0.68118546, 0.87769261, 0.00565494],
        [0.10655668, 0.48301942, 0.29354671]]])

In [329]:
np.random.randint(1,100,size=(2,3)) # 生成一个随机矩阵，矩阵的shape是(2,3)，元素都是随机的int，范围【1，99】

array([[17, 32, 39],
       [38, 37, 15]])

In [353]:
# 复制/重复 一个矩阵/数组 rename：重命名 refactor：重构   repeat：重复
l = np.repeat(a,5)
print(l)
ll = np.repeat(c,2,axis=0) # axis层级 axis=0代表第1层
print(c)
print('-----------------------')
print(ll)

[1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 4 4 4 4 4 5 5 5 5 5]
[[[ 11  12  13]
  [ 23  24  25]]

 [[ 35 360  37]
  [ 46  47  48]]]
-----------------------
[[[ 11  12  13]
  [ 23  24  25]]

 [[ 11  12  13]
  [ 23  24  25]]

 [[ 35 360  37]
  [ 46  47  48]]

 [[ 35 360  37]
  [ 46  47  48]]]


In [435]:
b = np.array([[11,12,13],[21,23,24]])
print(b)
print(b[1,2])  # 写法比较简单
print(b[1][2]) # 上下两种写法结果一样
print(b[0:2][1:2])  # 先取出b的第0,1个元素[11,12,13],[21,23,24],然后再取出前一个结果中的[1:2]第2个[21,23,24]

[[11 12 13]
 [21 23 24]]
24
24
[[21 23 24]]


##### 练习

In [382]:
arr5 = np.ones((5,5))
arr3 = np.zeros((3,3))
arr3[1,1] = 9
arr5[1:-1,1:-1] = arr3 # 把中间的部分替换掉
print(arr5)

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### numpy矩阵的复制。复制的时候要注意

In [386]:
arr = np.array([1,2,3,4,5])
arrc = arr # arrc是arr的一个复制
arrc[0] = 100
print(arr)
print(arrc)

[100   2   3   4   5]
[100   2   3   4   5]


In [390]:
arr2 = np.array([1,2,3,4,5])
arrc2=arr2.copy() # copy复制
arrc2[0] = 100
print(arr2)
print(arrc2)

[1 2 3 4 5]
[100   2   3   4   5]


### numpy矩阵的 + - * / **平方

In [408]:
a = np.array([1,2,3,4,5],dtype='int8') 
b = np.array([11,22,33,44,55],dtype='int8') 

In [399]:
a+1

array([2, 3, 4, 5, 6], dtype=int8)

In [400]:
a-1

array([0, 1, 2, 3, 4], dtype=int8)

In [401]:
a*2

array([ 2,  4,  6,  8, 10], dtype=int8)

In [402]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [404]:
a**2

array([ 1,  4,  9, 16, 25], dtype=int8)

In [422]:
print(a+b)
print(a-b)
print(a*b) # a*b 是两个矩阵的算术乘。 在数学中矩阵可以 点乘
print(a/b)

[[6 8]
 [6 6]]
[[-4 -4]
 [ 0  2]]
[[ 5 12]
 [ 9  8]]
[[0.2        0.33333333]
 [1.         2.        ]]


# 矩阵的乘法： 算术乘  点乘

In [418]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[3,2]])


In [419]:
a*b  # 算术乘

array([[ 5, 12],
       [ 9,  8]])

In [420]:
np.dot(a,b)  # c#.   dot Net  矩阵的点乘，左边的行x右边的列

array([[11, 10],
       [27, 26]])